### ISSUE TITLE
How does your program work?

### ISSUE THREAD

**Issue by ValadaresX** [Nezzquikk/NWMM-New-World-MiniMap#6]
is it memory reading? I'm afraid to use it and get banned.

**Comment by Nezzquikk** [comment]
It does screenshots of the game in order to get the player location in the top right corner when enabling "Show FPS" in the settings, so basically using the game's own features.

It's not memory reading, it's much safer. It's simply screenshotting the game, grabbing player position with OCR and showing position on a Map.

It's pretty simple technique but it's still up to you.

Have Fun :)
